// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaCreateClusterRequest See ConsulAMAService.CreateCluster
//
// swagger:model hashicorp.cloud.consulama.ama.CreateClusterRequest
type HashicorpCloudConsulamaAmaCreateClusterRequest struct {

	// id is the Azure resource ID of the new cluster.
	// Passed in the request body.
	ID string `json:"id,omitempty"`

	// name is the resource name of the new Consul cluster resource.
	// Passed in the request path and in the request body.
	Name string `json:"name,omitempty"`

	// properties are the properties of the new cluster.
	// Passed in the request body.
	Properties *HashicorpCloudConsulamaAmaClusterProperties `json:"properties,omitempty"`

	// resource_group is the resource group in which the new Consul cluster
	// should be created. This is the AMA instance's managed resource group.
	// Passed in the request path.
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// subscription_id is the ID of the Azure subscription the new Consul
	// cluster should be created in. This is the customer's subscription ID.
	// Passed in the request path.
	SubscriptionID string `json:"subscriptionId,omitempty"`

	// type is the Azure resource type of the new cluster.
	// Passed in the request body.
	Type string `json:"type,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama create cluster request
func (m *HashicorpCloudConsulamaAmaCreateClusterRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProperties(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaCreateClusterRequest) validateProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.Properties) { // not required
		return nil
	}

	if m.Properties != nil {
		if err := m.Properties.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("properties")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateClusterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateClusterRequest) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaCreateClusterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
