// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails BillingDetails contains billing related information about a managed app.
// swagger:model hashicorp.cloud.consulama.ama.ResourceNotificationRequest.BillingDetails
type HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails struct {

	// resource_usage_id is the id used identify the managed app when
	// emitting metered billing events to azure.
	ResourceUsageID string `json:"resourceUsageId,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama resource notification request billing details
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaResourceNotificationRequestBillingDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
