// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// HashicorpCloudConsulamaAmaBoolean Boolean is an enum for handling true/false values as Azure swagger validation doesn't
// like bools:
// https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r3018
//
// swagger:model hashicorp.cloud.consulama.ama.Boolean
type HashicorpCloudConsulamaAmaBoolean string

const (

	// HashicorpCloudConsulamaAmaBooleanFALSE captures enum value "FALSE"
	HashicorpCloudConsulamaAmaBooleanFALSE HashicorpCloudConsulamaAmaBoolean = "FALSE"

	// HashicorpCloudConsulamaAmaBooleanTRUE captures enum value "TRUE"
	HashicorpCloudConsulamaAmaBooleanTRUE HashicorpCloudConsulamaAmaBoolean = "TRUE"
)

// for schema
var hashicorpCloudConsulamaAmaBooleanEnum []interface{}

func init() {
	var res []HashicorpCloudConsulamaAmaBoolean
	if err := json.Unmarshal([]byte(`["FALSE","TRUE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudConsulamaAmaBooleanEnum = append(hashicorpCloudConsulamaAmaBooleanEnum, v)
	}
}

func (m HashicorpCloudConsulamaAmaBoolean) validateHashicorpCloudConsulamaAmaBooleanEnum(path, location string, value HashicorpCloudConsulamaAmaBoolean) error {
	if err := validate.EnumCase(path, location, value, hashicorpCloudConsulamaAmaBooleanEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud consulama ama boolean
func (m HashicorpCloudConsulamaAmaBoolean) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudConsulamaAmaBooleanEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
