// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage CurrentUsage describes what has been billed for a managed app in the current
// time period(s).
//
// swagger:model hashicorp.cloud.consulama.ama.GetBillingInfoResponse.CurrentUsage
type HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage struct {

	// time_period has usage data for multiple time frames.
	TimePeriod *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods `json:"timePeriod,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama get billing info response current usage
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimePeriod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage) validateTimePeriod(formats strfmt.Registry) error {

	if swag.IsZero(m.TimePeriod) { // not required
		return nil
	}

	if m.TimePeriod != nil {
		if err := m.TimePeriod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timePeriod")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
