// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaRestoreSnapshotRequest See ConsulAMAService.RestoreSnapshot
// swagger:model hashicorp.cloud.consulama.ama.RestoreSnapshotRequest
type HashicorpCloudConsulamaAmaRestoreSnapshotRequest struct {

	// resource_group is the resource group in which the Consul snapshot exists.
	// This is the AMA instance's managed resource group.
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// snapshot_id is the ID of the Consul snapshot to restore.
	SnapshotID string `json:"snapshotId,omitempty"`

	// subscription_id is the ID of the Azure subscription the Consul snapshot
	// exists in. This is the customer's subscription ID.
	SubscriptionID string `json:"subscriptionId,omitempty"`

	// take_snapshot determines if a snapshot should be taken before performing a restore.
	TakeSnapshot HashicorpCloudConsulamaAmaBoolean `json:"takeSnapshot,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama restore snapshot request
func (m *HashicorpCloudConsulamaAmaRestoreSnapshotRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTakeSnapshot(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaRestoreSnapshotRequest) validateTakeSnapshot(formats strfmt.Registry) error {

	if swag.IsZero(m.TakeSnapshot) { // not required
		return nil
	}

	if err := m.TakeSnapshot.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("takeSnapshot")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaRestoreSnapshotRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaRestoreSnapshotRequest) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaRestoreSnapshotRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
