// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetConfigResponse hashicorp cloud consulama ama get config response
// swagger:model hashicorp.cloud.consulama.ama.GetConfigResponse
type HashicorpCloudConsulamaAmaGetConfigResponse struct {

	// ca file
	CaFile string `json:"caFile,omitempty"`

	// client config
	ClientConfig string `json:"clientConfig,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama get config response
func (m *HashicorpCloudConsulamaAmaGetConfigResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetConfigResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
