// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HashicorpCloudConsulamaAmaClusterState ClusterState describes the current state a cluster is in. There is no DELETED
// state because after deletion clusters do not exist anymore and requests to
// retrieve them are responded to with not-found errors.
//
// These values are specific to our comminication with Azure, and they're not backed
// by our persistence layer. When the consul-ama service has to produce a cluster
// state to respond to a request from Azure, it reads the state from the consul-service
// and then translates the state value to one compatible with this enum.
// swagger:model hashicorp.cloud.consulama.ama.ClusterState
type HashicorpCloudConsulamaAmaClusterState string

const (

	// HashicorpCloudConsulamaAmaClusterStateUNSET captures enum value "UNSET"
	HashicorpCloudConsulamaAmaClusterStateUNSET HashicorpCloudConsulamaAmaClusterState = "UNSET"

	// HashicorpCloudConsulamaAmaClusterStatePENDING captures enum value "PENDING"
	HashicorpCloudConsulamaAmaClusterStatePENDING HashicorpCloudConsulamaAmaClusterState = "PENDING"

	// HashicorpCloudConsulamaAmaClusterStateCREATING captures enum value "CREATING"
	HashicorpCloudConsulamaAmaClusterStateCREATING HashicorpCloudConsulamaAmaClusterState = "CREATING"

	// HashicorpCloudConsulamaAmaClusterStateRUNNING captures enum value "RUNNING"
	HashicorpCloudConsulamaAmaClusterStateRUNNING HashicorpCloudConsulamaAmaClusterState = "RUNNING"

	// HashicorpCloudConsulamaAmaClusterStateFAILED captures enum value "FAILED"
	HashicorpCloudConsulamaAmaClusterStateFAILED HashicorpCloudConsulamaAmaClusterState = "FAILED"

	// HashicorpCloudConsulamaAmaClusterStateDELETING captures enum value "DELETING"
	HashicorpCloudConsulamaAmaClusterStateDELETING HashicorpCloudConsulamaAmaClusterState = "DELETING"
)

// for schema
var hashicorpCloudConsulamaAmaClusterStateEnum []interface{}

func init() {
	var res []HashicorpCloudConsulamaAmaClusterState
	if err := json.Unmarshal([]byte(`["UNSET","PENDING","CREATING","RUNNING","FAILED","DELETING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudConsulamaAmaClusterStateEnum = append(hashicorpCloudConsulamaAmaClusterStateEnum, v)
	}
}

func (m HashicorpCloudConsulamaAmaClusterState) validateHashicorpCloudConsulamaAmaClusterStateEnum(path, location string, value HashicorpCloudConsulamaAmaClusterState) error {
	if err := validate.Enum(path, location, value, hashicorpCloudConsulamaAmaClusterStateEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud consulama ama cluster state
func (m HashicorpCloudConsulamaAmaClusterState) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudConsulamaAmaClusterStateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
