// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension Dimension represents a billing dimension.
//
// swagger:model hashicorp.cloud.consulama.ama.GetBillingReportResponse.BilledItem.Dimension
type HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension struct {

	// name is the name of the billing dimension.
	Name string `json:"name,omitempty"`

	// tiers is the usage per tier in this dimension.
	Tiers []*HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimensionTier `json:"tiers"`
}

// Validate validates this hashicorp cloud consulama ama get billing report response billed item dimension
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension) validateTiers(formats strfmt.Registry) error {

	if swag.IsZero(m.Tiers) { // not required
		return nil
	}

	for i := 0; i < len(m.Tiers); i++ {
		if swag.IsZero(m.Tiers[i]) { // not required
			continue
		}

		if m.Tiers[i] != nil {
			if err := m.Tiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
