// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem BilledItem represents one time frame for which a specific billing plan
// was applied to the managed app.
//
// swagger:model hashicorp.cloud.consulama.ama.GetBillingReportResponse.BilledItem
type HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem struct {

	// cost is the total cost billed for the time frame.
	Cost float64 `json:"cost,omitempty"`

	// dimensions details what billing dimensions caused the cost.
	Dimensions []*HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItemDimension `json:"dimensions"`

	// end is the end time of the time frame.
	End string `json:"end,omitempty"`

	// plan is the name of the billing plan applied to the time frame.
	Plan string `json:"plan,omitempty"`

	// start is the start time of the time frame.
	Start string `json:"start,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama get billing report response billed item
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDimensions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem) validateDimensions(formats strfmt.Registry) error {

	if swag.IsZero(m.Dimensions) { // not required
		return nil
	}

	for i := 0; i < len(m.Dimensions); i++ {
		if swag.IsZero(m.Dimensions[i]) { // not required
			continue
		}

		if m.Dimensions[i] != nil {
			if err := m.Dimensions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dimensions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
