// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods CurrentUsagePeriods contains usage data for several time periods.
//
// swagger:model hashicorp.cloud.consulama.ama.GetBillingInfoResponse.CurrentUsagePeriods
type HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods struct {

	// this_moneth describes usage billed to the current month.
	ThisMonth *HashicorpCloudConsulamaAmaBilledUsage `json:"thisMonth,omitempty"`

	// today describes usage billed to the current day.
	Today *HashicorpCloudConsulamaAmaBilledUsage `json:"today,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama get billing info response current usage periods
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateThisMonth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToday(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods) validateThisMonth(formats strfmt.Registry) error {

	if swag.IsZero(m.ThisMonth) { // not required
		return nil
	}

	if m.ThisMonth != nil {
		if err := m.ThisMonth.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("thisMonth")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods) validateToday(formats strfmt.Registry) error {

	if swag.IsZero(m.Today) { // not required
		return nil
	}

	if m.Today != nil {
		if err := m.Today.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("today")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsagePeriods
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
