// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaClusterUpdate ClusterUpdate contains the details of the cluster which are requested
// to be updated.
// swagger:model hashicorp.cloud.consulama.ama.ClusterUpdate
type HashicorpCloudConsulamaAmaClusterUpdate struct {

	// consul_version is the Consul version to upgrade the cluster to.
	ConsulVersion string `json:"consulVersion,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama cluster update
func (m *HashicorpCloudConsulamaAmaClusterUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaClusterUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaClusterUpdate) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaClusterUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
