// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaACLToken ACLToken represents the Consul 1.4+ ACL token we just created.
//
// swagger:model hashicorp.cloud.consulama.ama.ACLToken
type HashicorpCloudConsulamaAmaACLToken struct {

	// accessor Id
	AccessorID string `json:"accessorId,omitempty"`

	// secret Id
	SecretID string `json:"secretId,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama ACL token
func (m *HashicorpCloudConsulamaAmaACLToken) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaACLToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaACLToken) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaACLToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
