// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaBillingSettings BillingSettings is the representation of the billing settings of a managed
// app that is exposed to users.
//
// swagger:model hashicorp.cloud.consulama.ama.BillingSettings
type HashicorpCloudConsulamaAmaBillingSettings struct {

	// active_since is the time since when the billing settings are active.
	ActiveSince string `json:"activeSince,omitempty"`

	// plan is the name of the billing plan. This is a simplified version of the
	// internal plan identifier:
	//    e.g. "annual" instead of "production-annual-through-hc"
	Plan string `json:"plan,omitempty"`

	// prices represents the prices of the current plan.
	Prices *HashicorpCloudConsulamaAmaBillingSettingsPrices `json:"prices,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama billing settings
func (m *HashicorpCloudConsulamaAmaBillingSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrices(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaBillingSettings) validatePrices(formats strfmt.Registry) error {

	if swag.IsZero(m.Prices) { // not required
		return nil
	}

	if m.Prices != nil {
		if err := m.Prices.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("prices")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaBillingSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaBillingSettings) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaBillingSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
