// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaResourceNotificationRequestError Error represents an error that happened in Azure when
// interacting with a managed app instance. It is optionally included in a
// ResourceNotificationRequest.
//
// swagger:model hashicorp.cloud.consulama.ama.ResourceNotificationRequest.Error
type HashicorpCloudConsulamaAmaResourceNotificationRequestError struct {

	// code is the error code of the failed operation, e.g.
	// "ResourceGroupDeletionBlocked"
	Code string `json:"code,omitempty"`

	// message is a human-readable description of the error.
	Message string `json:"message,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama resource notification request error
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaResourceNotificationRequestError) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaResourceNotificationRequestError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
