// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaFederatedClusterResponse FederatedClusterResponse contains minimal cluster information for identifying
// a cluster in a federation.
//
// swagger:model hashicorp.cloud.consulama.ama.FederatedClusterResponse
type HashicorpCloudConsulamaAmaFederatedClusterResponse struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// resource group
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// subscription Id
	SubscriptionID string `json:"subscriptionId,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama federated cluster response
func (m *HashicorpCloudConsulamaAmaFederatedClusterResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaFederatedClusterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaFederatedClusterResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaFederatedClusterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
