// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingInfoResponse See ConsulAMAService.GetBillingInfo.
// swagger:model hashicorp.cloud.consulama.ama.GetBillingInfoResponse
type HashicorpCloudConsulamaAmaGetBillingInfoResponse struct {

	// current_settings represents the currently active billing settings of the
	// app.
	CurrentSettings *HashicorpCloudConsulamaAmaBillingSettings `json:"currentSettings,omitempty"`

	// usage represents the billed usage of the current time period.
	Usage *HashicorpCloudConsulamaAmaGetBillingInfoResponseCurrentUsage `json:"usage,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama get billing info response
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponse) validateCurrentSettings(formats strfmt.Registry) error {

	if swag.IsZero(m.CurrentSettings) { // not required
		return nil
	}

	if m.CurrentSettings != nil {
		if err := m.CurrentSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("currentSettings")
			}
			return err
		}
	}

	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponse) validateUsage(formats strfmt.Registry) error {

	if swag.IsZero(m.Usage) { // not required
		return nil
	}

	if m.Usage != nil {
		if err := m.Usage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("usage")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingInfoResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingInfoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
