// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaListSnapshotsResponse See ConsulAMAService.ListSnapshots
//
// swagger:model hashicorp.cloud.consulama.ama.ListSnapshotsResponse
type HashicorpCloudConsulamaAmaListSnapshotsResponse struct {

	// snapshots is the list of snapshots in the format of SnapshotResponses.
	Snapshots []*HashicorpCloudConsulamaAmaSnapshotProperties `json:"snapshots"`
}

// Validate validates this hashicorp cloud consulama ama list snapshots response
func (m *HashicorpCloudConsulamaAmaListSnapshotsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSnapshots(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaListSnapshotsResponse) validateSnapshots(formats strfmt.Registry) error {

	if swag.IsZero(m.Snapshots) { // not required
		return nil
	}

	for i := 0; i < len(m.Snapshots); i++ {
		if swag.IsZero(m.Snapshots[i]) { // not required
			continue
		}

		if m.Snapshots[i] != nil {
			if err := m.Snapshots[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("snapshots" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaListSnapshotsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaListSnapshotsResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaListSnapshotsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
