// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaBilledUsagePlanUsage PlanUsage describes the usage billed based on a single plan.
//
// swagger:model hashicorp.cloud.consulama.ama.BilledUsage.PlanUsage
type HashicorpCloudConsulamaAmaBilledUsagePlanUsage struct {

	// hours describes how many hours were consumed on this plan.
	Hours float64 `json:"hours,omitempty"`

	// plan is the name of the billing plan.
	Plan string `json:"plan,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama billed usage plan usage
func (m *HashicorpCloudConsulamaAmaBilledUsagePlanUsage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaBilledUsagePlanUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaBilledUsagePlanUsage) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaBilledUsagePlanUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
