// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaVersion Version is a consul cluster version used in upgrade scenarios.
// swagger:model hashicorp.cloud.consulama.ama.Version
type HashicorpCloudConsulamaAmaVersion struct {

	// status defines the version availability.
	Status HashicorpCloudConsulamaAmaVersionStatus `json:"status,omitempty"`

	// version is the string representation of the Consul version.
	Version string `json:"version,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama version
func (m *HashicorpCloudConsulamaAmaVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaVersion) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaVersion) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
