// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaCreateSnapshotRequest See ConsulAMAService.CreateSnapshot
// swagger:model hashicorp.cloud.consulama.ama.CreateSnapshotRequest
type HashicorpCloudConsulamaAmaCreateSnapshotRequest struct {

	// name is the resource name of the new Consul snapshot resource.
	// Passed in the request path.
	Name string `json:"name,omitempty"`

	// resource_group is the resource group in which the new Consul snapshot
	// should be created. This is the AMA instance's managed resource group.
	// Passed in the request path.
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// subscription_id is the ID of the Azure subscription the new Consul
	// snapshot should be created in. This is the customer's subscription ID.
	// Passed in the request path.
	SubscriptionID string `json:"subscriptionId,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama create snapshot request
func (m *HashicorpCloudConsulamaAmaCreateSnapshotRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateSnapshotRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateSnapshotRequest) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaCreateSnapshotRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
