// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaGetBillingReportResponse See ConsulAMAService.GetBillingReport.
// swagger:model hashicorp.cloud.consulama.ama.GetBillingReportResponse
type HashicorpCloudConsulamaAmaGetBillingReportResponse struct {

	// usage contains the usage that was recorded for the requested month.
	// There is one entry in this list per applied plan per hour.
	Usage []*HashicorpCloudConsulamaAmaGetBillingReportResponseBilledItem `json:"usage"`
}

// Validate validates this hashicorp cloud consulama ama get billing report response
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaGetBillingReportResponse) validateUsage(formats strfmt.Registry) error {

	if swag.IsZero(m.Usage) { // not required
		return nil
	}

	for i := 0; i < len(m.Usage); i++ {
		if swag.IsZero(m.Usage[i]) { // not required
			continue
		}

		if m.Usage[i] != nil {
			if err := m.Usage[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("usage" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaGetBillingReportResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaGetBillingReportResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
