// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaCreateTokenRequest CreateTokenRequest creates a token for the sole cluster found using this subscription ID and managed resource group.
// swagger:model hashicorp.cloud.consulama.ama.CreateTokenRequest
type HashicorpCloudConsulamaAmaCreateTokenRequest struct {

	// resource group
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// subscription Id
	SubscriptionID string `json:"subscriptionId,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama create token request
func (m *HashicorpCloudConsulamaAmaCreateTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateTokenRequest) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaCreateTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
