// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HashicorpCloudConsulamaAmaVersionStatus Status defines the version availability metadata.
//
//  - AVAILABLE: AVAILABLE represents a version that is generally available
// but no longer the preferred/recommended version.
//  - RECOMMENDED: RECOMMENDED represents a version that is generally available
// and recommended by HashiCorp.
//  - PREVIEW: PREVIEW represents a version that is not generally available.
// swagger:model hashicorp.cloud.consulama.ama.Version.Status
type HashicorpCloudConsulamaAmaVersionStatus string

const (

	// HashicorpCloudConsulamaAmaVersionStatusAVAILABLE captures enum value "AVAILABLE"
	HashicorpCloudConsulamaAmaVersionStatusAVAILABLE HashicorpCloudConsulamaAmaVersionStatus = "AVAILABLE"

	// HashicorpCloudConsulamaAmaVersionStatusRECOMMENDED captures enum value "RECOMMENDED"
	HashicorpCloudConsulamaAmaVersionStatusRECOMMENDED HashicorpCloudConsulamaAmaVersionStatus = "RECOMMENDED"

	// HashicorpCloudConsulamaAmaVersionStatusPREVIEW captures enum value "PREVIEW"
	HashicorpCloudConsulamaAmaVersionStatusPREVIEW HashicorpCloudConsulamaAmaVersionStatus = "PREVIEW"
)

// for schema
var hashicorpCloudConsulamaAmaVersionStatusEnum []interface{}

func init() {
	var res []HashicorpCloudConsulamaAmaVersionStatus
	if err := json.Unmarshal([]byte(`["AVAILABLE","RECOMMENDED","PREVIEW"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudConsulamaAmaVersionStatusEnum = append(hashicorpCloudConsulamaAmaVersionStatusEnum, v)
	}
}

func (m HashicorpCloudConsulamaAmaVersionStatus) validateHashicorpCloudConsulamaAmaVersionStatusEnum(path, location string, value HashicorpCloudConsulamaAmaVersionStatus) error {
	if err := validate.Enum(path, location, value, hashicorpCloudConsulamaAmaVersionStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud consulama ama version status
func (m HashicorpCloudConsulamaAmaVersionStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudConsulamaAmaVersionStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
