// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HashicorpCloudConsulamaAmaCreateTokenResponse CreateTokenResponse contains the new Consul Master Token.
// swagger:model hashicorp.cloud.consulama.ama.CreateTokenResponse
type HashicorpCloudConsulamaAmaCreateTokenResponse struct {

	// master token
	MasterToken *HashicorpCloudConsulamaAmaACLToken `json:"masterToken,omitempty"`
}

// Validate validates this hashicorp cloud consulama ama create token response
func (m *HashicorpCloudConsulamaAmaCreateTokenResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMasterToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudConsulamaAmaCreateTokenResponse) validateMasterToken(formats strfmt.Registry) error {

	if swag.IsZero(m.MasterToken) { // not required
		return nil
	}

	if m.MasterToken != nil {
		if err := m.MasterToken.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("masterToken")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateTokenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudConsulamaAmaCreateTokenResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudConsulamaAmaCreateTokenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
