// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HashicorpCloudConsulamaAmaGetFederationResponseFederationState FederationState describes the current state of a federation.
//
//  - UNKNOWN: UNKNOWN is the default value; it indicates that the value is not set.
//  - RUNNING: RUNNING means the federation is in a healthy state.
//  - PRIMARY_DATACENTER_MISSING: PRIMARY_DATACENTER_MISSING means the federation's primary cluster has been deleted.
// Any remaining secondary clusters can still communicate, but new clusters cannot be added to the federation.
// swagger:model hashicorp.cloud.consulama.ama.GetFederationResponse.FederationState
type HashicorpCloudConsulamaAmaGetFederationResponseFederationState string

const (

	// HashicorpCloudConsulamaAmaGetFederationResponseFederationStateUNKNOWN captures enum value "UNKNOWN"
	HashicorpCloudConsulamaAmaGetFederationResponseFederationStateUNKNOWN HashicorpCloudConsulamaAmaGetFederationResponseFederationState = "UNKNOWN"

	// HashicorpCloudConsulamaAmaGetFederationResponseFederationStateRUNNING captures enum value "RUNNING"
	HashicorpCloudConsulamaAmaGetFederationResponseFederationStateRUNNING HashicorpCloudConsulamaAmaGetFederationResponseFederationState = "RUNNING"

	// HashicorpCloudConsulamaAmaGetFederationResponseFederationStatePRIMARYDATACENTERMISSING captures enum value "PRIMARY_DATACENTER_MISSING"
	HashicorpCloudConsulamaAmaGetFederationResponseFederationStatePRIMARYDATACENTERMISSING HashicorpCloudConsulamaAmaGetFederationResponseFederationState = "PRIMARY_DATACENTER_MISSING"
)

// for schema
var hashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum []interface{}

func init() {
	var res []HashicorpCloudConsulamaAmaGetFederationResponseFederationState
	if err := json.Unmarshal([]byte(`["UNKNOWN","RUNNING","PRIMARY_DATACENTER_MISSING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum = append(hashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum, v)
	}
}

func (m HashicorpCloudConsulamaAmaGetFederationResponseFederationState) validateHashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum(path, location string, value HashicorpCloudConsulamaAmaGetFederationResponseFederationState) error {
	if err := validate.Enum(path, location, value, hashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this hashicorp cloud consulama ama get federation response federation state
func (m HashicorpCloudConsulamaAmaGetFederationResponseFederationState) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateHashicorpCloudConsulamaAmaGetFederationResponseFederationStateEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
